name: Test AutoGitPush

on:
  push:
    branches: [ "SideBranch" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create dummy repo with a file
        run: |
          mkdir dummy-repo && cd dummy-repo
          git init -b main
          echo "Initial content" > file.txt
          git add file.txt
          git commit -m "Initial commit"
        
          git remote add origin https://github.com/${GITHUB_REPOSITORY}.git
          git fetch origin

          git checkout -b SideBranch || git checkout SideBranch
          git push -u origin SideBranch

          cd ..

      - name: Update config file for dummy repo
        run: |
            CONFIG_FILE=$(find . -type f -name "autogitpush.conf" | head -n 1)
            echo "Found config at: $CONFIG_FILE"
            sed -i "s|^REPO_PATH=.*|REPO_PATH=./dummy-repo|" "$CONFIG_FILE"
            sed -i "s|^INTERVAL=.*|INTERVAL=5|" "$CONFIG_FILE"


      - name: Modify dummy file every 3 sec in background
        run: |
          (
            for i in {1..10}; do
              echo "Update $i at $(date)" >> dummy-repo/file.txt
              sleep 3
            done
          ) &

      - name: Run AutoGitPush for 30 sec then kill
        run: |
            SCRIPT=$(find . -type f -name "gitautoB.sh" | head -n 1)
            echo "Found script at: $SCRIPT"
            chmod +x "$SCRIPT"
            timeout 30s "$SCRIPT"

